services:
  # 🐘 PostgreSQL
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_USER=mlflow_user
      - POSTGRES_PASSWORD=mlflow_password
      - POSTGRES_DB=mlflow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mlflow_user", "-d", "mlflow_db"]
      interval: 30s
      retries: 3
      timeout: 5s
      start_period: 10s
  
  # 📊 MLflow
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.1.0
    container_name: mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --default-artifact-root /mlflow
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3
      timeout: 5s
      start_period: 10s

volumes:
  mlflow_data:
  postgres_data:
